CREATE TABLE `conversationStates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`conversationId` varchar(36) NOT NULL,
	`leadId` int,
	`name` varchar(255),
	`phone` varchar(20),
	`email` varchar(320),
	`emailSkipped` int NOT NULL DEFAULT 0,
	`classFor` enum('self','child','other'),
	`childAge` int,
	`segment` enum('KIDS_3_5','KIDS_6_12','TEENS','ADULTS','KICKBOXING','CAMP','AFTER_SCHOOL'),
	`introRequired` int NOT NULL DEFAULT 0,
	`introBookedCount` int NOT NULL DEFAULT 0,
	`askedKeys` text,
	`nextStep` varchar(50) NOT NULL DEFAULT 'NAME',
	`location` varchar(255),
	`program` varchar(100),
	`introSlots` text,
	`trialSlot` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `conversationStates_id` PRIMARY KEY(`id`),
	CONSTRAINT `conversationStates_conversationId_unique` UNIQUE(`conversationId`)
);
