CREATE TABLE `manualEnrollments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentName` varchar(255) NOT NULL,
	`parentName` varchar(255),
	`phone` varchar(30) NOT NULL,
	`email` varchar(320),
	`program` enum('kickboxing','martial_arts','summer_camp','after_school') NOT NULL,
	`customPrice` decimal(10,2) NOT NULL,
	`billingFrequency` enum('monthly','weekly') NOT NULL,
	`nextChargeDate` varchar(10) NOT NULL,
	`preAuthEnabled` int NOT NULL DEFAULT 0,
	`preAuthTransactionId` varchar(64),
	`fluidpayCustomerId` varchar(64),
	`fluidpaySubscriptionId` varchar(64),
	`initialTransactionId` varchar(64),
	`cardLast4` varchar(4),
	`cardType` varchar(32),
	`status` enum('pending','active','cancelled','failed') NOT NULL DEFAULT 'pending',
	`notes` text,
	`createdByStaffId` int,
	`createdByStaffName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `manualEnrollments_id` PRIMARY KEY(`id`)
);
