CREATE TABLE `customPaymentLinkPayments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`linkId` int NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`customerEmail` varchar(320),
	`customerPhone` varchar(20),
	`amountCharged` decimal(10,2) NOT NULL,
	`fluidpayTransactionId` varchar(64),
	`fluidpayCustomerId` varchar(64),
	`fluidpaySubscriptionId` varchar(64),
	`cardLast4` varchar(4),
	`cardType` varchar(32),
	`status` enum('pending','approved','declined','failed') NOT NULL DEFAULT 'pending',
	`merchandiseItems` json,
	`shippingAddress` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `customPaymentLinkPayments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `customPaymentLinks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`token` varchar(64) NOT NULL,
	`type` enum('one_time','recurring','merchandise') NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`amount` decimal(10,2),
	`billingInterval` enum('weekly','monthly','yearly'),
	`billingCycles` int,
	`merchandiseItems` json,
	`requiresShipping` int NOT NULL DEFAULT 0,
	`isActive` int NOT NULL DEFAULT 1,
	`expiresAt` timestamp,
	`createdByStaffId` int,
	`createdByStaffName` varchar(255),
	`useCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customPaymentLinks_id` PRIMARY KEY(`id`),
	CONSTRAINT `customPaymentLinks_token_unique` UNIQUE(`token`)
);
