import { ArrowRight, Check, Compass, HeartHandshake, ShieldCheck } from "lucide-react";
import SEO from "@/components/SEO";
import SchemaMarkup from "@/components/SchemaMarkup";
import { openBookFreeClassGate } from "@/lib/chatbot";

export default function About() {
  return (
    <div className="public-page min-h-screen">
      <SEO title="About MyDojo Martial Arts & Fitness" description="Learn how MyDojo creates a focused, supportive martial arts experience for children, teens, and adults in Tomball, Texas." />
      <SchemaMarkup type="LocalBusiness" />
      <SchemaMarkup type="BreadcrumbList" items={[{ name: "Home", url: "/" }, { name: "About Us", url: "/about" }]} />

      <section className="relative overflow-hidden bg-black py-20 text-white md:py-28"><img src="https://files.manuscdn.com/manus-storage/master-holmes-stance_86d12feb.jpeg" alt="MyDojo martial arts instruction" className="absolute inset-0 h-full w-full object-cover opacity-35" /><div className="absolute inset-0 bg-black/60" /><div className="container relative z-10 grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><p className="text-[0.7rem] font-extrabold uppercase tracking-[0.2em] text-[#e63946]">About MyDojo</p><h1 className="mt-5 font-heading text-[clamp(4rem,8vw,8rem)] font-bold uppercase leading-[0.84] tracking-[-0.045em]">Built for<br />better days.</h1></div><p className="max-w-2xl text-lg leading-8 text-white/80">MyDojo is a place to work hard, feel supported, and keep moving forward. We use martial arts as a practical way to help students build confidence, discipline, fitness, and a stronger sense of what they can do.</p></div></section>

      <section className="public-section bg-[var(--mydojo-paper)]"><div className="container grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="public-eyebrow">Why we teach</p><h2 className="public-title mt-5">The lesson reaches beyond the mat.</h2></div><div className="max-w-2xl"><p className="public-copy">Martial arts training gives students a clear path: show up, practice deliberately, face a challenge, and recognize progress. The physical work matters, but the habits formed in the process matter just as much.</p><div className="public-rule mt-9" /><div className="mt-7 grid gap-3 text-sm font-semibold text-zinc-700 sm:grid-cols-2">{["Focused instruction", "Supportive accountability", "Meaningful progression", "A welcoming dojo culture"].map((item) => <span key={item} className="flex items-center gap-2"><Check className="h-4 w-4 text-[#e63946]" />{item}</span>)}</div></div></div></section>

      <section className="bg-white py-16 md:py-24"><div className="container grid border-l border-t border-[var(--mydojo-line)] md:grid-cols-3">{[{ icon: Compass, number: "01", title: "Clear direction", copy: "Students always know what they are practicing, why it matters, and what their next milestone can be." }, { icon: HeartHandshake, number: "02", title: "Real encouragement", copy: "Coaching is direct, positive, and grounded in helping each student build confidence through effort." }, { icon: ShieldCheck, number: "03", title: "A standard of respect", copy: "We lead with discipline, safety, care for others, and responsibility for ourselves." }].map(({ icon: Icon, number, title, copy }) => <article key={number} className="border-b border-r border-[var(--mydojo-line)] p-8 md:p-10"><div className="flex items-start justify-between"><Icon className="h-6 w-6 text-[#e63946]" /><span className="font-heading text-5xl font-bold text-zinc-200">{number}</span></div><h2 className="mt-12 font-heading text-4xl font-bold uppercase leading-none text-black">{title}</h2><p className="mt-5 text-sm leading-7 text-zinc-600">{copy}</p></article>)}</div></section>

      <section className="bg-black text-white"><div className="container grid min-h-[38rem] lg:grid-cols-2"><div className="relative min-h-[21rem] overflow-hidden lg:min-h-0"><img src="https://files.manuscdn.com/manus-storage/master-holmes-headshot_cd686d71.jpg" alt="Master Vincent Holmes" className="h-full w-full object-cover object-top grayscale-[10%]" /><div className="absolute bottom-0 left-0 bg-[#e63946] px-5 py-4 text-xs font-extrabold uppercase tracking-[0.13em]">Master Vincent Holmes</div></div><div className="flex flex-col justify-center py-16 lg:px-20"><p className="text-[0.7rem] font-extrabold uppercase tracking-[0.2em] text-[#e63946]">Leadership at MyDojo</p><h2 className="mt-5 font-heading text-[clamp(3.4rem,5vw,5.5rem)] font-bold uppercase leading-[0.87] tracking-[-0.04em]">A dojo led<br />with purpose.</h2><p className="mt-7 max-w-xl text-base leading-7 text-white/75">Master Vincent Holmes and the MyDojo team bring the same standard to every student: offer clear coaching, create a strong culture, and help people recognize the progress they earn.</p><button onClick={openBookFreeClassGate} className="public-button mt-9 w-fit">Meet the team in class <ArrowRight className="h-4 w-4" /></button></div></div></section>

      <section className="bg-[#e63946] py-16 text-white md:py-24"><div className="container flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-[0.7rem] font-extrabold uppercase tracking-[0.2em] text-white/70">Take the first step</p><h2 className="mt-5 font-heading text-[clamp(3.4rem,6vw,6rem)] font-bold uppercase leading-[0.86] tracking-[-0.04em]">Come train<br />with us.</h2></div><button onClick={openBookFreeClassGate} className="inline-flex min-h-[3.125rem] items-center justify-center gap-2 bg-black px-5 text-xs font-extrabold uppercase tracking-[0.12em] text-white hover:bg-white hover:text-black">Book a free class <ArrowRight className="h-4 w-4" /></button></div></section>
    </div>
  );
}
