import { ArrowRight, Check, Flame, HeartPulse, ShieldCheck, Zap } from "lucide-react";
import { Link } from "wouter";
import SEO from "@/components/SEO";
import { openBookFreeClassGate } from "@/lib/chatbot";

const CDN = "https://d2xsxph8kpxj0f.cloudfront.net/310419663031545745/Lu5Er8YqGDyrsXYnbeua3C";

const DISCIPLINES = [
  { title: "Kickboxing", label: "Cardio · conditioning · striking", image: `${CDN}/kickboxing-bg_d4fcc4c5.webp`, copy: "High-energy classes that pair practical technique with a full-body workout and the momentum of training alongside a community.", href: "/programs/kickboxing" },
  { title: "Adult Karate", label: "Discipline · technique · progress", image: `${CDN}/teens-adults_e35f9895.webp`, copy: "A focused, structured martial arts practice that helps adults build skill, discipline, and confidence through clear goals.", href: "/programs/adult-karate" },
];

export default function AdultKickboxing() {
  return (
    <div className="public-page">
      <SEO title="Adult Kickboxing in Tomball | MyDojo" description="Adult kickboxing and karate classes in Tomball for all experience levels. Train for fitness, self-defense, confidence, and progress." />
      <section className="relative min-h-[calc(100svh-4rem)] overflow-hidden bg-black md:min-h-[calc(100svh-6rem)]"><img src={`${CDN}/kickboxing-bg_d4fcc4c5.webp`} alt="Adult kickboxing at MyDojo" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-black/60" /><div className="container relative z-10 flex min-h-[calc(100svh-4rem)] items-end py-14 md:min-h-[calc(100svh-6rem)] md:py-20"><div className="max-w-3xl text-white"><p className="text-[0.7rem] font-extrabold uppercase tracking-[0.2em] text-white/75">MyDojo adult training</p><h1 className="mt-5 font-heading text-[clamp(4.2rem,10vw,9rem)] font-bold uppercase leading-[0.82] tracking-[-0.045em]">Your strongest<br /><span className="text-[#e63946]">hour starts here.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/85 md:text-lg">Build strength, sharpen your mindset, and learn practical skills through kickboxing and karate classes designed for real people with real goals.</p><button onClick={openBookFreeClassGate} className="public-button mt-9">Book a free class <ArrowRight className="h-4 w-4" /></button></div></div></section>

      <section className="bg-white py-16 md:py-24"><div className="container grid border-l border-t border-[var(--mydojo-line)] sm:grid-cols-2 lg:grid-cols-4">{[{ icon: Flame, title: "Work with energy", copy: "A motivating format that helps you show up, stay engaged, and leave feeling accomplished." }, { icon: ShieldCheck, title: "Learn real skills", copy: "Technique and self-defense awareness taught with clarity, safety, and purpose." }, { icon: Zap, title: "Build momentum", copy: "A balanced practice for conditioning, coordination, confidence, and stress relief." }, { icon: HeartPulse, title: "Train with people", copy: "A welcoming community that makes challenging yourself feel possible." }].map(({ icon: Icon, title, copy }) => <article key={title} className="border-b border-r border-[var(--mydojo-line)] p-7 md:p-8"><Icon className="h-6 w-6 text-[#e63946]" /><h2 className="mt-7 font-heading text-3xl font-bold uppercase leading-none text-black">{title}</h2><p className="mt-4 text-sm leading-6 text-zinc-600">{copy}</p></article>)}</div></section>

      <section className="public-section bg-[var(--mydojo-paper)]"><div className="container"><div className="mb-12 grid gap-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-end"><div><p className="public-eyebrow">Choose a discipline</p><h2 className="public-title mt-5">Train for more.</h2></div><p className="public-copy max-w-xl">Whether you are here for a better workout, self-defense skills, a new challenge, or a reset from the day, the first step is simply showing up.</p></div><div className="grid border-l border-t border-[var(--mydojo-line)] md:grid-cols-2">{DISCIPLINES.map((discipline) => <article key={discipline.title} className="group border-b border-r border-[var(--mydojo-line)] bg-white"><img src={discipline.image} alt={discipline.title} className="h-72 w-full object-cover grayscale-[10%] transition duration-500 group-hover:scale-[1.02] group-hover:grayscale-0" /><div className="p-8"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-[#e63946]">{discipline.label}</p><h2 className="mt-4 font-heading text-5xl font-bold uppercase leading-none text-black">{discipline.title}</h2><p className="mt-5 text-sm leading-6 text-zinc-600">{discipline.copy}</p><ul className="mt-6 space-y-2 text-sm text-zinc-700">{["Welcoming for beginners", "Clear coaching and progression", "A focused community"].map((point) => <li key={point} className="flex items-center gap-2"><Check className="h-4 w-4 text-[#e63946]" />{point}</li>)}</ul><div className="mt-8 flex gap-5"><Link href={discipline.href}><span className="inline-flex cursor-pointer items-center gap-1.5 text-xs font-extrabold uppercase tracking-[0.12em] text-black hover:text-[#e63946]">Explore <ArrowRight className="h-4 w-4" /></span></Link><button onClick={openBookFreeClassGate} className="text-xs font-extrabold uppercase tracking-[0.12em] text-[#e63946] hover:text-[#bf2634]">Book intro</button></div></div></article>)}</div></div></section>

      <section className="bg-black py-16 text-white md:py-24"><div className="container grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-end"><div><p className="text-[0.7rem] font-extrabold uppercase tracking-[0.2em] text-[#e63946]">Start without pressure</p><h2 className="mt-5 font-heading text-[clamp(3.5rem,7vw,6.5rem)] font-bold uppercase leading-[0.86] tracking-[-0.04em]">The first class<br />is the hardest<br />to book.</h2></div><div><p className="max-w-xl text-base leading-7 text-white/75">It is also the easiest place to discover what you are capable of. Start with a complimentary introduction, meet the team, and see how MyDojo feels in person.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={openBookFreeClassGate} className="public-button">Book your class <ArrowRight className="h-4 w-4" /></button><Link href="/locations/tomball"><span className="inline-flex min-h-[3.125rem] cursor-pointer items-center justify-center border border-white px-5 text-xs font-extrabold uppercase tracking-[0.12em] text-white hover:bg-white hover:text-black">Visit Tomball HQ</span></Link></div></div></div></section>
    </div>
  );
}
