import { useState } from "react";
import { useSearch } from "wouter";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Loader2, ShieldCheck, Users } from "lucide-react";

export default function FamilyEnrollment() {
  const search = useSearch();
  const params = new URLSearchParams(search);
  const [name, setName] = useState(params.get("name") || "");
  const [email, setEmail] = useState(params.get("email") || "");
  const [phone, setPhone] = useState(params.get("phone") || "");
  const success = params.get("success") === "1";
  const cancelled = params.get("cancelled") === "1";
  const checkout = trpc.family.createStripeRegistrationCheckout.useMutation({ onSuccess: ({ checkoutUrl }) => window.location.assign(checkoutUrl) });
  const ready = name.trim().length > 1 && /\S+@\S+\.\S+/.test(email);

  if (success) return <main className="min-h-screen bg-slate-50 px-4 py-16"><section className="mx-auto max-w-md rounded-3xl border border-emerald-100 bg-white p-8 text-center shadow-xl"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-600" /><h1 className="mt-5 text-3xl font-bold text-slate-950">Family registration confirmed.</h1><p className="mt-3 leading-6 text-slate-600">Your family account is ready. The MyDojo team will help you add each family member and select their memberships.</p><a href="/" className="mt-7 inline-flex rounded-xl bg-primary px-5 py-3 font-semibold text-white">Return to MyDojo</a></section></main>;

  return <main className="min-h-screen bg-slate-50 px-4 py-12"><section className="mx-auto max-w-lg"><header className="text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-primary text-white"><Users className="h-7 w-7" /></div><p className="mt-5 text-xs font-bold uppercase tracking-[0.18em] text-primary">MyDojo family membership</p><h1 className="mt-2 text-4xl font-bold text-slate-950">Train together.</h1><p className="mt-3 text-slate-600">Create your family account with a one-time $99 registration fee. Additional family members receive member savings.</p></header>{cancelled && <p className="mt-6 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-center text-sm text-amber-800">Checkout was cancelled. No payment was made.</p>}<section className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="rounded-2xl bg-slate-50 p-4"><p className="font-semibold text-slate-950">Family registration</p><p className="mt-1 text-sm text-slate-600">One payment covers your family account setup.</p><p className="mt-3 text-3xl font-bold text-slate-950">$99.00</p></div><div className="mt-6 space-y-4"><label className="block text-sm font-semibold text-slate-800">Primary contact name<input value={name} onChange={(event) => setName(event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label><label className="block text-sm font-semibold text-slate-800">Email<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label><label className="block text-sm font-semibold text-slate-800">Phone <span className="font-normal text-slate-400">(optional)</span><input value={phone} onChange={(event) => setPhone(event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-3 font-normal" /></label></div><button disabled={!ready || checkout.isPending} onClick={() => checkout.mutate({ primaryContactName: name.trim(), primaryContactEmail: email.trim(), primaryContactPhone: phone.trim() || undefined, origin: window.location.origin })} className="mt-6 flex h-13 w-full items-center justify-center rounded-xl bg-primary px-5 py-3 font-bold text-white disabled:opacity-50">{checkout.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Opening secure checkout…</> : "Continue securely · $99.00"}</button><p className="mt-4 flex items-center justify-center gap-1 text-center text-xs text-slate-500"><ShieldCheck className="h-3.5 w-3.5 text-emerald-600" />Your payment details are encrypted and never stored by MyDojo.</p></section></section></main>;
}
