export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  DOJO_FLOW_URL: process.env.DOJO_FLOW_URL ?? "",
  DOJO_FLOW_EMAIL: process.env.DOJO_FLOW_EMAIL ?? "",
  DOJO_FLOW_PASSWORD: process.env.DOJO_FLOW_PASSWORD ?? "",
  RESEND_API_KEY: process.env.RESEND_API_KEY ?? "",
  EMAIL_FROM: process.env.VITE_EMAIL_FROM ?? "noreply@mydojoma.com",
  FLUIDPAY_WEBHOOK_SECRET: process.env.FLUIDPAY_WEBHOOK_SECRET ?? "",
  GHL_API_KEY: process.env.GHL_API_KEY ?? "",
};
